### PR TITLE
Add ESLint-problems as gutter-markers

### PR DESCRIPTION
**Pull request by djusv**
implementation based on code found in [brackets-git](https://github.com/zaggino/brackets-git) and [interactive-linter](https://github.com/MiguelCastillo/Brackets-InteractiveLinter).

These changes will only add a colored circle as a gutter-marker on the correct line. No gutter-click support, will look into next.

result:

### CODE REVIEW

**Comment by zaggino** [comment]
I'll need to test this ... in the meantime, aren't there a bit nicer icons to use for this? Or maybe at least a bit smaller.

**Comment by zaggino** [comment]
also, make these gutters optional so they can be turned off in settings

**Comment by djusv** [comment]
@zaggino will work on both suggestions.

**Comment by djusv** [comment]
I added 2 .svgs and also added the possibilty to disable the gutter.
preview:

**Comment by djusv** [comment]
I added some other icons and placed a readme.txt next to them for more info.
Also updated README.md to include configuration of  `brackets.json`.




@zaggino do you have any other suggestions or comments?

**Comment by zaggino** [comment]
:+1: Looks great, will merge it when I get some free time.

**Comment by zaggino** [comment]
Works fine, sometimes I hit this though when the marks doesn't play well with brackets-git gutter:

image

Don't know exactly what sequence of steps is causing this.

**Comment by djusv** [comment]
@zaggino I will investigate when I have some free time. Probably has todo with the gutter not having it's own width.

**Pull request merged**
